version: '3.8'
services:
  frontend:
    image: antoniopapa1991/admin-frontend
    depends_on:
      - admin
    networks:
      - app

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: admin_db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8004:8000
    depends_on:
      - admin_db
    networks:
      - app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    environment:
      DB_HOST: admin_db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - admin_db
    networks:
      - app

  admin_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33071:3306
    networks:
      - app

networks:
  app:
